[package]
name = "cufarul"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.10"
erased-serde = "0.3.28"
serde = { version = "1.0.174", features = ["derive"] }
serde_json = "1.0.104"
toml = "0.7.6"
